"use client";
import React from "react";

const translations = {
  ES: {
    newChat: "NUEVO CHAT",
    actions: "ACCIONES",
    createDoc: "Crear Documento",
    reviewDoc: "Revisar Documento",
    cases: "Casos",
    saved: "Guardado",
    share: "Compartir",
    export: "Exportar",
    heading2: "Título 2",
    comment: "Comentar",
    aiTools: "Herramientas IA",
    pageInfo: "Página 1 / 4",
    confidentialDraft: "Borrador Confidencial",
    docTitle: "CONTRATO DE ARRENDAMIENTO COMERCIAL",
    docP1: "Este Contrato de Arrendamiento Comercial (el \"Contrato\") se celebra este",
    docDate: "15 de octubre de 2023",
    docP2: ", por y entre:",
    docLandlord: "Propietario:",
    docLandlordDesc: "Horizon Property Management LLC, una corporación organizada bajo las leyes de Delaware, con sede en 100 Financial District Blvd, New York, NY (\"Propietario\").",
    docTenant: "Inquilino:",
    docTenantDesc: "Nexus Technology Group Inc., una corporación organizada bajo las leyes de California, con sede en 450 Innovation Drive, San Francisco, CA (\"Inquilino\").",
    grantOfLease: "1. Otorgamiento del Arrendamiento",
    grantOfLeaseDesc: "El Propietario, en consideración al alquiler a pagar y a los acuerdos a cumplir por parte del Inquilino, por la presente arrienda al Inquilino la propiedad descrita en el Anexo A adjunto (las \"Instalaciones\").",
    generatedBy: "Generado por LexIA",
    permittedUse: "2. Uso Permitido",
    permittedUseDesc1: "El Inquilino deberá usar y ocupar las Instalaciones únicamente para el propósito de operar una oficina de desarrollo tecnológico y funciones administrativas. El Inquilino no permitirá que las Instalaciones se usen para ningún propósito ilegal ni de manera que perturbe a otros. ",
    permittedUseDesc2: "El Inquilino tiene estrictamente prohibido almacenar materiales peligrosos en las Instalaciones.",
    term: "3. Plazo",
    termDesc: "El plazo de este Arrendamiento será por un período de sesenta (60) meses, comenzando el 1 de noviembre de 2023, y terminando el 31 de octubre de 2028, a menos que termine antes según las disposiciones del presente.",
    instructPlaceholder: "Instruye a LexIA para reescribir, resumir o añadir cláusulas...",
    generate: "GENERAR",
    aiAssistant: "ASISTENTE IA",
    assistantMessage: "Estoy analizando la sección de responsabilidad de 'Smith v. GlobalCorp'. ¿En qué te puedo ayudar con tu borrador?",
    askPlaceholder: "Pregúntale a LexIA...",
    createBtn: "CREAR",
    createBtnDesc: "Generar documentos desde cero",
    adviseBtn: "ASESORAR",
    adviseBtnDesc: "Resolver consultas o casos legales",
    reviewBtn: "REVISAR",
    reviewBtnDesc: "Analizar documentos subidos",
    langEs: "Español (ES)",
    langEn: "English (EN)",
  },
  EN: {
    newChat: "NEW CHAT",
    actions: "ACTIONS",
    createDoc: "Create Document",
    reviewDoc: "Review Document",
    cases: "Cases",
    saved: "Saved",
    share: "Share",
    export: "Export",
    heading2: "Heading 2",
    comment: "Comment",
    aiTools: "AI Tools",
    pageInfo: "Page 1 / 4",
    confidentialDraft: "Confidential Draft",
    docTitle: "COMMERCIAL LEASE AGREEMENT",
    docP1: "This Commercial Lease Agreement (the \"Agreement\") is made and entered into on this",
    docDate: "15th day of October, 2023",
    docP2: ", by and between:",
    docLandlord: "Landlord:",
    docLandlordDesc: "Horizon Property Management LLC, a corporation organized under the laws of Delaware, with its principal place of business at 100 Financial District Blvd, New York, NY (\"Landlord\").",
    docTenant: "Tenant:",
    docTenantDesc: "Nexus Technology Group Inc., a corporation organized under the laws of California, with its principal place of business at 450 Innovation Drive, San Francisco, CA (\"Tenant\").",
    grantOfLease: "1. Grant of Lease",
    grantOfLeaseDesc: "Landlord, in consideration of the rent to be paid and the covenants and agreements to be performed and observed by the Tenant, does hereby lease to the Tenant and the Tenant does hereby lease and take from the Landlord the property described in Exhibit A attached hereto (the \"Premises\").",
    generatedBy: "Generated by LexIA",
    permittedUse: "2. Permitted Use",
    permittedUseDesc1: "The Tenant shall use and occupy the Premises solely for the purpose of operating a technology development office, general administrative functions, and related business activities. The Tenant shall not use or permit the Premises to be used for any illegal purpose or in any manner that would constitute a nuisance or disturb the quiet enjoyment of other tenants in the building. ",
    permittedUseDesc2: "The Tenant is strictly prohibited from storing hazardous materials on the Premises.",
    term: "3. Term",
    termDesc: "The term of this Lease shall be for a period of sixty (60) months, commencing on November 1, 2023 (the \"Commencement Date\"), and terminating on October 31, 2028 (the \"Termination Date\"), unless sooner terminated pursuant to any provision hereof.",
    instructPlaceholder: "Instruct LexIA to rewrite, summarize, or add clauses...",
    generate: "GENERATE",
    aiAssistant: "AI ASSISTANT",
    assistantMessage: "I am analyzing the liability section of 'Smith v. GlobalCorp'. How can I assist with your draft?",
    askPlaceholder: "Ask LexIA...",
    createBtn: "CREATE",
    createBtnDesc: "Generate documents from scratch",
    adviseBtn: "ADVISE",
    adviseBtnDesc: "Resolve legal queries or cases",
    reviewBtn: "REVIEW",
    reviewBtnDesc: "Analyze uploaded documents",
    langEs: "Español (ES)",
    langEn: "English (EN)",
  }
};

export default function LexiaAssistant() {
  const [langMenuOpen, setLangMenuOpen] = React.useState(false);
  const [currentLang, setCurrentLang] = React.useState('ES');
  const [isDarkMode, setIsDarkMode] = React.useState(false);
  const [modality, setModality] = React.useState('ASISTENTE');
  const t = translations[currentLang];
  const [leftWidth, setLeftWidth] = React.useState(280);
  const [rightWidth, setRightWidth] = React.useState(400);
  const [isResizingLeft, setIsResizingLeft] = React.useState(false);
  const [isResizingRight, setIsResizingRight] = React.useState(false);

  React.useEffect(() => {
    const handleMouseMove = (e) => {
      if (isResizingLeft) {
        setLeftWidth(Math.max(200, Math.min(e.clientX, window.innerWidth * 0.5)));
      } else if (isResizingRight) {
        setRightWidth(Math.max(250, Math.min(window.innerWidth - e.clientX, window.innerWidth * 0.5)));
      }
    };

    const handleMouseUp = () => {
      setIsResizingLeft(false);
      setIsResizingRight(false);
    };

    if (isResizingLeft || isResizingRight) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    };
  }, [isResizingLeft, isResizingRight]);

  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html: `
        /* Custom styles */
        @layer base{html,body{margin:0;padding:0;}body{overscroll-behavior:none;}main>:first-child{margin-top:0!important;}main>:last-child{margin-bottom:0!important;}}::-webkit-scrollbar{display:none;}
      `,
        }}
      />
      <div className={`${isDarkMode ? 'dark ' : ''}h-screen w-screen overflow-hidden flex flex-col font-body-ui-md bg-background text-on-surface`}>
        <aside 
          className="fixed left-0 top-14 h-[calc(100vh-3.5rem)] bg-surface-container-low z-50 flex flex-col border-r border-outline-variant/30"
          style={{ width: `${leftWidth}px` }}
        >
          <div
            className="absolute right-0 top-0 w-2 h-full cursor-col-resize hover:bg-primary/20 z-50 transition-colors"
            onMouseDown={() => setIsResizingLeft(true)}
          ></div>
          <div className="px-stack-md my-stack-md">
            <button className="w-full flex items-center justify-center gap-stack-sm bg-primary text-on-primary py-stack-sm rounded-lg font-label-caps hover:bg-primary-container transition-colors">
              <span className="material-symbols-outlined text-[18px]">add</span>
              {t.newChat}
            </button>
          </div>
          <nav
            className="flex-1 px-stack-md overflow-y-auto space-y-1"
            data-active-classes="bg-secondary-container text-on-secondary-container font-bold"
          >
            <div className="text-on-surface-variant font-label-caps text-[10px] px-stack-sm py-stack-sm mt-stack-md">
              {t.actions}
            </div>
            <a
              aria-current="page"
              className="flex items-center px-stack-sm py-stack-sm rounded-lg transition-all bg-secondary-container text-on-secondary-container font-bold"
              data-path="crear-documento"
              href="#"
            >
              <span className="material-symbols-outlined mr-3">note_add</span>
              {t.createDoc}
            </a>
            <a
              className="flex items-center px-stack-sm py-stack-sm rounded-lg text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface transition-all"
              data-path="revisar-documento"
              href="#"
            >
              <span className="material-symbols-outlined mr-3">
                fact_check
              </span>
              {t.reviewDoc}
            </a>
          </nav>
        </aside>
        <div style={{ paddingLeft: `${leftWidth}px`, paddingRight: `${rightWidth}px` }}>
          <header className="fixed top-0 left-0 w-full h-14 bg-surface/80 backdrop-blur-xl border-b border-outline-variant/30 z-[60] flex items-center justify-between px-stack-lg">
            <div className="flex items-center">
              <img src="/logo.png" alt="LexIA Logo" className="h-8 w-auto object-contain" />
            </div>
            <div className="flex items-center gap-stack-md">
              <button 
                onClick={() => setIsDarkMode(!isDarkMode)}
                className="flex items-center justify-center text-on-surface-variant hover:text-on-surface transition-colors hover:bg-surface-container-high w-8 h-8 rounded-md"
                title={isDarkMode ? "Modo Claro" : "Modo Oscuro"}
              >
                <span className="material-symbols-outlined text-[18px]">
                  {isDarkMode ? "light_mode" : "dark_mode"}
                </span>
              </button>
              <div className="relative">
                <button 
                  onClick={() => setLangMenuOpen(!langMenuOpen)}
                  className="flex items-center gap-1 text-on-surface-variant hover:text-on-surface transition-colors hover:bg-surface-container-high px-2 py-1 rounded-md"
                >
                  <span className="material-symbols-outlined text-[18px]">
                    language
                  </span>
                  <span className="text-xs font-bold">{currentLang}</span>
                  <span className="material-symbols-outlined text-[16px]">
                    expand_more
                  </span>
                </button>
                {langMenuOpen && (
                  <div className="absolute top-full right-0 mt-1 w-32 bg-surface-container-lowest border border-outline-variant/30 rounded-lg shadow-lg py-1 z-50 flex flex-col">
                    <button 
                      onClick={() => {setCurrentLang('ES'); setLangMenuOpen(false);}}
                      className={`text-left px-3 py-2 text-sm hover:bg-surface-container-high transition-colors ${currentLang === 'ES' ? 'text-primary font-bold' : 'text-on-surface'}`}
                    >
                      {t.langEs}
                    </button>
                    <button 
                      onClick={() => {setCurrentLang('EN'); setLangMenuOpen(false);}}
                      className={`text-left px-3 py-2 text-sm hover:bg-surface-container-high transition-colors ${currentLang === 'EN' ? 'text-primary font-bold' : 'text-on-surface'}`}
                    >
                      {t.langEn}
                    </button>
                  </div>
                )}
              </div>
              <div className="h-6 w-px bg-outline-variant/50 mx-stack-sm"></div>
              <img
                src="https://lh3.googleusercontent.com/aida-public/AB6AXuCyXLlLzzfKIXyZ7QV5sGUY5NBYGpc7lScZtY1d7nF9GL2OPnyfZ0IrdSYcLq1Jx2zpKF819l77qRw-N2hhyLaHqbsdgj1ATdvHGg1t1s4jv3EMWgvffwH4HXxM3A26hQYdLqZMW6E-Oo8w_5CkLHVA1U9tZoMf08y6aLdqmM0n_3aCJq-mHQuO9vubDgH8qqM1aFrhoyR3eH1-8fswrA_M_9qNnINtVxYDP4hZvyntdUM-Jc0uTWGgUZJtyrY3UPk8iXc"
                alt="User Avatar"
                className="h-8 w-auto object-contain rounded-full"
              />
            </div>
          </header>
          <main className="relative pt-14 min-h-screen bg-surface">
            <div className="flex flex-col w-full h-full relative font-body-md bg-surface text-on-surface">
              <div className="flex w-full h-[calc(100vh-3.5rem)]">
                <section className="flex-1 h-full flex flex-col bg-surface relative overflow-hidden">
                  <div className="h-12 bg-surface flex items-center px-6 gap-2 text-on-surface-variant flex-shrink-0 z-10 sticky top-0 shadow-[0_4px_24px_-12px_rgba(0,0,0,0.05)]">
                    <div className="flex items-center gap-1">
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center font-bold text-lg bg-surface-container-low text-primary shadow-[inset_0_1px_2px_rgba(255,255,255,0.8)] shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
                        B
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center italic text-lg">
                        I
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center underline text-lg">
                        U
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center line-through text-lg text-outline">
                        S
                      </button>
                    </div>
                    <div className="w-px h-5 bg-outline-variant/40 mx-2"></div>
                    <div className="flex items-center gap-1">
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_left
                        </span>
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_center
                        </span>
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_justify
                        </span>
                      </button>
                    </div>
                    <div className="w-px h-5 bg-outline-variant/40 mx-2"></div>
                    <div className="flex items-center gap-1">
                      <button className="px-3 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center gap-1">
                        <span className="text-sm font-medium">{t.heading2}</span>
                        <span className="material-symbols-outlined text-[16px]">
                          expand_more
                        </span>
                      </button>
                    </div>
                    <div className="flex-1">
                      <div className="flex justify-center items-center h-full opacity-20">
                        <img
                          src="https://lh3.googleusercontent.com/aida-public/AB6AXuDLOMTUQRJqbAc2Wbu0-aIUU0FNgVYFFVeYT2A_NPfB94GNLWtE9J0ZGFYwUHiFI8VY7lRk5BPQDydr9zsfnBK1w35u5qz1_NhbSFS1nBR_UhN_MFKsWFJeEcSaAIPQFF81BmgRXBGXz8WJmNsrCrMnG7I7m5k2nM2_X5dJk-UCHGfJXZp9puHk9sjvIkhdphGUqn0KOGrXHZ4v4KclvuFQci8zHMBk29YcFhwOdWyzZMXyRNzMWCMSr686HH1I1DNNzLU"
                          className="h-6 w-6 object-contain"
                        />
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button className="h-8 px-3 rounded-lg bg-surface-container text-on-surface hover:bg-surface-container-high transition-colors flex items-center gap-1.5 shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
                        <span className="material-symbols-outlined text-[16px]">
                          add_comment
                        </span>
                        <span className="text-[13px] font-medium">{t.comment}</span>
                      </button>
                      <button className="h-8 px-3 rounded-lg bg-primary-container text-on-primary-container hover:bg-primary-container/90 transition-colors flex items-center gap-1.5 shadow-[0_2px_4px_rgba(13,28,50,0.1)]">
                        <span
                          className="material-symbols-outlined text-[16px]"
                          style={{ fontVariationSettings: "&quot" }}
                        >
                          magic_button
                        </span>
                        <span className="text-[13px] font-medium">
                          {t.aiTools}
                        </span>
                      </button>
                    </div>
                  </div>

                  <div className="flex-1 overflow-y-auto px-8 py-12 relative flex justify-center pb-32">
                    <div className="w-full max-w-[760px] bg-surface-container-lowest min-h-[900px] shadow-[0_8px_30px_-4px_rgba(0,0,0,0.08)] shadow-[0_4px_12px_-2px_rgba(0,0,0,0.03)] px-16 py-20 relative group text-[#2d3133]">
                      <div className="absolute top-8 right-16 text-outline font-code-sm text-[11px] tracking-wider uppercase">
                        {t.pageInfo}
                      </div>
                      <div className="absolute top-8 left-16 text-outline font-code-sm text-[11px] tracking-wider uppercase">
                        {t.confidentialDraft}
                      </div>
                      <div className="font-headline-xl text-center text-primary mb-12 tracking-tight">
                        {t.docTitle}
                      </div>
                      <p className="font-body-lg text-[#44474d] mb-8 leading-relaxed">
                        {t.docP1}{" "}
                        <span className="bg-surface-container-high px-1 rounded-sm text-primary font-medium cursor-pointer hover:bg-primary/10 transition-colors">
                          {t.docDate}
                        </span>
                        {t.docP2}
                      </p>
                      <div className="pl-8 border-l-[3px] border-outline-variant/30 mb-8 space-y-4 font-body-lg">
                        <div className="">
                          <strong>{t.docLandlord}</strong> {t.docLandlordDesc}
                        </div>
                        <div className="">
                          <strong>{t.docTenant}</strong> {t.docTenantDesc}
                        </div>
                      </div>
                      <h2 className="font-headline-lg text-primary mt-12 mb-6">
                        {t.grantOfLease}
                      </h2>
                      <p className="font-body-lg text-[#44474d] mb-6 leading-relaxed">
                        {t.grantOfLeaseDesc}
                      </p>

                      <div className="relative my-8 rounded-xl bg-secondary/5 p-[1px] group/ai">
                        <div className="absolute -left-12 top-4 opacity-0 group-hover/ai:opacity-100 transition-opacity">
                          <button className="w-8 h-8 rounded-full bg-surface shadow-md flex items-center justify-center text-secondary hover:bg-secondary hover:text-on-secondary transition-colors">
                            <span className="material-symbols-outlined text-[18px]">
                              edit_note
                            </span>
                          </button>
                        </div>
                        <div className="absolute top-0 right-0 -mt-2 -mr-2 bg-secondary text-on-secondary text-[10px] font-label-caps px-2 py-0.5 rounded shadow-sm flex items-center gap-1 z-10">
                          <span
                            className="material-symbols-outlined text-[12px]"
                            style={{ fontVariationSettings: "&quot" }}
                          >
                            auto_awesome
                          </span>
                          {t.generatedBy}
                        </div>
                        <div className="bg-surface-container-lowest p-6 rounded-[11px]">
                          <h2 className="font-title-md text-primary mb-4 flex items-center gap-2">
                            <span className="w-1 h-5 bg-secondary rounded-full block"></span>
                            {t.permittedUse}
                          </h2>
                          <p className="font-body-lg text-[#44474d] leading-relaxed">
                            {t.permittedUseDesc1}
                            <span className="bg-secondary/20 text-on-surface font-medium px-1 rounded-sm shadow-[0_1px_0_rgba(119,90,25,0.5)] cursor-pointer">
                              {t.permittedUseDesc2}
                            </span>
                          </p>
                        </div>
                        <div className="absolute bottom-0 right-4 translate-y-1/2 opacity-0 group-hover/ai:opacity-100 transition-opacity flex gap-1 z-10">
                          <button className="bg-surface shadow-md text-outline hover:text-primary p-1.5 rounded-md">
                            <span className="material-symbols-outlined text-[16px]">
                              thumb_up
                            </span>
                          </button>
                          <button className="bg-surface shadow-md text-outline hover:text-primary p-1.5 rounded-md">
                            <span className="material-symbols-outlined text-[16px]">
                              thumb_down
                            </span>
                          </button>
                          <button className="bg-surface shadow-md text-outline hover:text-primary p-1.5 rounded-md">
                            <span className="material-symbols-outlined text-[16px]">
                              refresh
                            </span>
                          </button>
                        </div>
                      </div>
                      <h2 className="font-headline-lg text-primary mt-12 mb-6">
                        {t.term}
                      </h2>
                      <p className="font-body-lg text-[#44474d] mb-6 leading-relaxed">
                        {t.termDesc}
                      </p>

                      <div className="mt-8 flex items-start gap-3 opacity-60">
                        <span className="material-symbols-outlined text-secondary animate-pulse mt-1">
                          edit_document
                        </span>
                        <div className="flex-1">
                          <div className="h-4 w-3/4 bg-surface-container-high rounded animate-pulse mb-2"></div>
                          <div className="h-4 w-1/2 bg-surface-container-high rounded animate-pulse"></div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="absolute bottom-8 left-1/2 -translate-x-1/2 w-full max-w-lg z-20">
                    <div className="bg-surface/80 backdrop-blur-xl p-2 rounded-2xl shadow-[0_8px_32px_rgba(0,0,0,0.12)] shadow-[0_0_0_1px_rgba(226,232,240,0.8)] flex items-center gap-2 transition-transform hover:-translate-y-1 duration-300">
                      <div className="w-10 h-10 rounded-full bg-secondary/10 flex items-center justify-center text-secondary shrink-0 ml-1">
                        <span
                          className="material-symbols-outlined"
                          style={{ fontVariationSettings: "&quot" }}
                        >
                          magic_button
                        </span>
                      </div>
                      <input
                        className="flex-1 bg-transparent border-none text-[15px] font-body-md text-primary placeholder-on-surface-variant focus:outline-none focus:ring-0 px-2 h-full min-w-0"
                        placeholder={t.instructPlaceholder}
                        type="text"
                      />
                      <button className="h-10 px-4 rounded-xl bg-primary text-on-primary font-label-caps hover:bg-primary/90 transition-colors shrink-0 shadow-[0_2px_8px_rgba(0,0,0,0.2)]">
                        {t.generate}
                      </button>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </main>
        </div>
      <aside
        className="fixed right-0 top-14 h-[calc(100vh-3.5rem)] bg-surface-container-lowest border-l border-outline-variant/30 z-50 flex flex-col"
        style={{ width: `${rightWidth}px` }}
      >
        <div
          className="absolute left-0 top-0 w-2 h-full cursor-col-resize hover:bg-primary/20 z-50 transition-colors"
          onMouseDown={() => setIsResizingRight(true)}
        ></div>
        <div className="w-full h-full flex flex-col">
          <div className="h-14 flex items-center px-stack-md border-b border-outline-variant/20 bg-surface-container-low">
            <div className="w-10 h-10 rounded-full overflow-hidden border border-outline-variant/30 mr-3 shrink-0">
              <img
                src="https://lh3.googleusercontent.com/aida-public/AB6AXuBdKMOoSQ45-xqB_Cf9hAjG79pYqVNrkQo0xpMw0a2clEYC7rxCw-B-3S7yiH9OcrpypudA2k3MWsv8mPnjuo3T7UwX0SmWwsVhFlA75qq-quCQzEm07FI43mUZqz0jP6MVzfw-CcDmeRVATpsITUvserdRufUUS3wSoMnI43lwsOpGFN4MsEWNanNs0Rm4WnTqdp9UhJ3c1S6FIuq7SXrinPmQ6-moBD4jM3XFqRuDU5GD7Io5iJ6rCgPg7c2RFrN3XtA"
                className="w-full h-full object-cover"
                alt="AI Mascot"
              />
            </div>
            <div className="flex bg-surface-container-highest rounded-lg p-1 border border-outline-variant/20 gap-1">
              {[
                { id: 'ASISTENTE', icon: 'support_agent', title: t.createBtnDesc },
                { id: 'ASESORA', icon: 'balance', title: t.adviseBtnDesc },
                { id: 'AUDITORA', icon: 'fact_check', title: t.reviewBtnDesc }
              ].map(mod => (
                <button
                  key={mod.id}
                  onClick={() => setModality(mod.id)}
                  title={mod.title}
                  className={`flex items-center gap-1 px-2.5 py-1.5 rounded-md text-[10px] font-bold transition-all ${
                    modality === mod.id
                      ? 'bg-surface shadow-sm text-primary'
                      : 'text-on-surface-variant hover:text-on-surface hover:bg-surface/50'
                  }`}
                >
                  <span className="material-symbols-outlined text-[14px]">{mod.icon}</span>
                  {mod.id}
                </button>
              ))}
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-stack-md space-y-stack-md">
            <div className="bg-surface-container p-stack-sm rounded-lg text-xs text-on-surface-variant border-l-4 border-secondary">
              {t.assistantMessage}
            </div>
          </div>
          <div className="p-stack-md border-t border-outline-variant/20 bg-surface-container-low">
            <div className="relative">
              <textarea
                className="w-full bg-surface-container-lowest border border-outline-variant rounded-xl p-stack-sm text-sm focus:outline-none focus:ring-1 focus:ring-secondary resize-none h-24"
                placeholder={t.askPlaceholder}
              ></textarea>
              <button className="absolute right-2 bottom-2 text-secondary hover:text-on-secondary-container transition-colors">
                <span className="material-symbols-outlined">send</span>
              </button>
            </div>
          </div>
        </div>
      </aside>
      </div>
    </>
  );
}
