"use client";
import React from "react";
import { marked } from "marked";
import TiptapEditor from "../components/TiptapEditor";

const translations = {
  ES: {
    newChat: "NUEVO CHAT",
    actions: "ACCIONES",
    createDoc: "Crear Documento",
    reviewDoc: "Revisar Documento",
    cases: "Casos",
    saved: "Guardado",
    share: "Compartir",
    export: "Exportar",
    heading2: "Título 2",
    comment: "Comentar",
    aiTools: "Herramientas IA",
    pageInfo: "Página 1 / 4",
    confidentialDraft: "Borrador Confidencial",
    docTitle: "CONTRATO DE ARRENDAMIENTO COMERCIAL",
    docP1: "Este Contrato de Arrendamiento Comercial (el \"Contrato\") se celebra este",
    docDate: "15 de octubre de 2023",
    docP2: ", por y entre:",
    docLandlord: "Propietario:",
    docLandlordDesc: "Horizon Property Management LLC, una corporación organizada bajo las leyes de Delaware, con sede en 100 Financial District Blvd, New York, NY (\"Propietario\").",
    docTenant: "Inquilino:",
    docTenantDesc: "Nexus Technology Group Inc., una corporación organizada bajo las leyes de California, con sede en 450 Innovation Drive, San Francisco, CA (\"Inquilino\").",
    grantOfLease: "1. Otorgamiento del Arrendamiento",
    grantOfLeaseDesc: "El Propietario, en consideración al alquiler a pagar y a los acuerdos a cumplir por parte del Inquilino, por la presente arrienda al Inquilino la propiedad descrita en el Anexo A adjunto (las \"Instalaciones\").",
    generatedBy: "Generado por LexIA",
    permittedUse: "2. Uso Permitido",
    permittedUseDesc1: "El Inquilino deberá usar y ocupar las Instalaciones únicamente para el propósito de operar una oficina de desarrollo tecnológico y funciones administrativas. El Inquilino no permitirá que las Instalaciones se usen para ningún propósito ilegal ni de manera que perturbe a otros. ",
    permittedUseDesc2: "El Inquilino tiene estrictamente prohibido almacenar materiales peligrosos en las Instalaciones.",
    term: "3. Plazo",
    termDesc: "El plazo de este Arrendamiento será por un período de sesenta (60) meses, comenzando el 1 de noviembre de 2023, y terminando el 31 de octubre de 2028, a menos que termine antes según las disposiciones del presente.",
    instructPlaceholder: "Instruye a LexIA para reescribir, resumir o añadir cláusulas...",
    generate: "GENERAR",
    aiAssistant: "ASISTENTE IA",
    assistantMessage: "Estoy analizando la sección de responsabilidad de 'Smith v. GlobalCorp'. ¿En qué te puedo ayudar con tu borrador?",
    askPlaceholder: "Pregúntale a LexIA...",
    createBtn: "CREAR",
    createBtnDesc: "Generar documentos desde cero",
    adviseBtn: "ASESORAR",
    adviseBtnDesc: "Resolver consultas o casos legales",
    reviewBtn: "REVISAR",
    reviewBtnDesc: "Analizar documentos subidos",
    langEs: "Español (ES)",
    langEn: "English (EN)",
  },
  EN: {
    newChat: "NEW CHAT",
    actions: "ACTIONS",
    createDoc: "Create Document",
    reviewDoc: "Review Document",
    cases: "Cases",
    saved: "Saved",
    share: "Share",
    export: "Export",
    heading2: "Heading 2",
    comment: "Comment",
    aiTools: "AI Tools",
    pageInfo: "Page 1 / 4",
    confidentialDraft: "Confidential Draft",
    docTitle: "COMMERCIAL LEASE AGREEMENT",
    docP1: "This Commercial Lease Agreement (the \"Agreement\") is made and entered into on this",
    docDate: "15th day of October, 2023",
    docP2: ", by and between:",
    docLandlord: "Landlord:",
    docLandlordDesc: "Horizon Property Management LLC, a corporation organized under the laws of Delaware, with its principal place of business at 100 Financial District Blvd, New York, NY (\"Landlord\").",
    docTenant: "Tenant:",
    docTenantDesc: "Nexus Technology Group Inc., a corporation organized under the laws of California, with its principal place of business at 450 Innovation Drive, San Francisco, CA (\"Tenant\").",
    grantOfLease: "1. Grant of Lease",
    grantOfLeaseDesc: "Landlord, in consideration of the rent to be paid and the covenants and agreements to be performed and observed by the Tenant, does hereby lease to the Tenant and the Tenant does hereby lease and take from the Landlord the property described in Exhibit A attached hereto (the \"Premises\").",
    generatedBy: "Generated by LexIA",
    permittedUse: "2. Permitted Use",
    permittedUseDesc1: "The Tenant shall use and occupy the Premises solely for the purpose of operating a technology development office, general administrative functions, and related business activities. The Tenant shall not use or permit the Premises to be used for any illegal purpose or in any manner that would constitute a nuisance or disturb the quiet enjoyment of other tenants in the building. ",
    permittedUseDesc2: "The Tenant is strictly prohibited from storing hazardous materials on the Premises.",
    term: "3. Term",
    termDesc: "The term of this Lease shall be for a period of sixty (60) months, commencing on November 1, 2023 (the \"Commencement Date\"), and terminating on October 31, 2028 (the \"Termination Date\"), unless sooner terminated pursuant to any provision hereof.",
    instructPlaceholder: "Instruct LexIA to rewrite, summarize, or add clauses...",
    generate: "GENERATE",
    aiAssistant: "AI ASSISTANT",
    assistantMessage: "I am analyzing the liability section of 'Smith v. GlobalCorp'. How can I assist with your draft?",
    askPlaceholder: "Ask LexIA...",
    createBtn: "CREATE",
    createBtnDesc: "Generate documents from scratch",
    adviseBtn: "ADVISE",
    adviseBtnDesc: "Resolve legal queries or cases",
    reviewBtn: "REVIEW",
    reviewBtnDesc: "Analyze uploaded documents",
    langEs: "Español (ES)",
    langEn: "English (EN)",
  }
};

export default function LexiaAssistant() {
  const [langMenuOpen, setLangMenuOpen] = React.useState(false);
  const [currentLang, setCurrentLang] = React.useState('ES');
  const [isDarkMode, setIsDarkMode] = React.useState(false);
  const [modality, setModality] = React.useState('ASISTENTE');
  const t = translations[currentLang];
  const [leftWidth, setLeftWidth] = React.useState(280);
  const [rightWidth, setRightWidth] = React.useState(400);
  const [isResizingLeft, setIsResizingLeft] = React.useState(false);
  const [isResizingRight, setIsResizingRight] = React.useState(false);

  const [chatsByModality, setChatsByModality] = React.useState({
    ASISTENTE: [],
    ASESORA: [],
    AUDITORA: []
  });
  
  const [editorTabs, setEditorTabs] = React.useState([
    { id: 'tab_default', title: 'Documento 1', content: '' }
  ]);
  const [activeTabId, setActiveTabId] = React.useState('tab_default');
  
  const [activeConversations, setActiveConversations] = React.useState({
    ASISTENTE: `conv_${Date.now()}_ASISTENTE`,
    ASESORA: `conv_${Date.now()}_ASESORA`,
    AUDITORA: `conv_${Date.now()}_AUDITORA`
  });
  
  const [inputValue, setInputValue] = React.useState("");
  const [isChatLoading, setIsChatLoading] = React.useState(false);
  const [attachedFiles, setAttachedFiles] = React.useState([]);
  const fileInputRef = React.useRef(null);
  const fileInputRefAuditora = React.useRef(null);
  const chatEndRef = React.useRef(null);
  const occurrencesCache = React.useRef({});
  const [scrollToLastBlock, setScrollToLastBlock] = React.useState(false);
  const [correctedErrors, setCorrectedErrors] = React.useState(new Set());

  React.useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatsByModality, modality, isChatLoading]);

  React.useEffect(() => {
    if (scrollToLastBlock) {
      const timer = setTimeout(() => {
        const editorContainers = document.querySelectorAll('.ProseMirror');
        for (const container of editorContainers) {
          if (container.offsetParent !== null) { // if visible
            const hrs = container.querySelectorAll('hr');
            if (hrs.length > 0) {
              hrs[hrs.length - 1].scrollIntoView({ behavior: 'smooth', block: 'start' });
            } else {
              container.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
            break;
          }
        }
        setScrollToLastBlock(false);
      }, 200);
      return () => clearTimeout(timer);
    }
  }, [scrollToLastBlock, editorTabs]);

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      const newFiles = Array.from(e.target.files).map(file => {
        return new Promise((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            resolve({
              name: file.name,
              type: file.type,
              base64: reader.result.split(',')[1] // extract base64
            });
          };
          reader.readAsDataURL(file);
        });
      });
      Promise.all(newFiles).then(files => {
        handleSendMessage(files);
      });
    }
  };

  const handleAuditoraFileChange = async (e) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      
      const extractText = async (f) => {
        if (f.type === "application/pdf") {
          const pdfjsLib = await import('pdfjs-dist/build/pdf.mjs');
          pdfjsLib.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;
          const arrayBuffer = await f.arrayBuffer();
          const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
          let text = '';
          for (let i = 1; i <= pdf.numPages; i++) {
            const page = await pdf.getPage(i);
            const content = await page.getTextContent();
            text += content.items.map(item => item.str).join(' ') + '\n';
          }
          return text;
        } else if (f.name.endsWith(".docx") || f.type.includes("wordprocessingml")) {
          const mammoth = await import('mammoth/mammoth.browser');
          const arrayBuffer = await f.arrayBuffer();
          const result = await mammoth.extractRawText({ arrayBuffer });
          return result.value;
        } else {
          return new Promise((resolve) => {
            const textReader = new FileReader();
            textReader.onloadend = () => resolve(textReader.result);
            textReader.readAsText(f);
          });
        }
      };
      
      const readAsBase64 = new Promise((resolve) => {
        const b64Reader = new FileReader();
        b64Reader.onloadend = () => {
          resolve({
            name: file.name,
            type: file.type,
            base64: b64Reader.result.split(',')[1]
          });
        };
        b64Reader.readAsDataURL(file);
      });

      try {
        const [textContent, fileData] = await Promise.all([extractText(file), readAsBase64]);
        const fileName = fileData.name;
        const currentConvId = activeConversations['AUDITORA'];
        const tabIdForConv = `auditoria_${currentConvId}`;
        
        let displayHtml = textContent || '';
        if (!fileData.type.includes('html')) {
          displayHtml = displayHtml
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/\n/g, '<br/>');
        }
        
        const htmlContent = displayHtml;
        
        setEditorTabs(prevTabs => {
          const existingTabIndex = prevTabs.findIndex(t => t.id === tabIdForConv);
          if (existingTabIndex >= 0) {
             let newTabs = [...prevTabs];
             newTabs[existingTabIndex].content = htmlContent;
             setTimeout(() => setActiveTabId(tabIdForConv), 0);
             return newTabs;
          } else {
             const auditoriaTabs = prevTabs.filter(t => t.id.startsWith('auditoria_'));
             let newTabs = [...prevTabs];
             if (auditoriaTabs.length >= 3) {
                newTabs = newTabs.filter(t => t.id !== auditoriaTabs[0].id);
             }
             const newTab = { id: tabIdForConv, title: `AUDITORÍA - ${fileName.substring(0, 15)}`, content: htmlContent };
             newTabs.push(newTab);
             setTimeout(() => setActiveTabId(tabIdForConv), 0);
             return newTabs;
          }
        });

        const customInstruction = `Analiza el documento adjunto y presenta el resultado de la siguiente manera estructurada:

1. TIPO DE DOCUMENTO: Indica únicamente el tipo de documento.
2. PARTICIPANTES: Lista cada participante como un bloque, línea por línea. Por ejemplo:
MANDANTE (o la calidad que corresponda)
- Nombre: [nombre]
- DUI: [números]
- Dirección: [dirección]

3. RESULTADO DE AUDITORÍA (Solo para hallazgos complejos):
Analiza el documento en busca de inconsistencias legales, problemas estructurales o riesgos importantes. IMPORTANTE: NO incluyas aquí los errores ortográficos menores, errores de redacción simple o números que deban ser letras (esos se manejan aparte). Tampoco consideres como hallazgos los problemas de concordancia plural/singular, ni los espacios en blanco o líneas "______" (esos espacios están a propósito para que los rellene el consulado). Para cada problema legal o estructural complejo, detállalo exactamente así (mantén las explicaciones MUY breves y directas al grano):

Hallazgo [Número] — [Título breve]
Tipo: [Estructural / Legal / Inconsistencia]
Sección: [Dónde se encuentra]
Problema: [Explicación breve y corta del problema]
Riesgo: [Riesgo breve si no se corrige]
Corrección propuesta: [Propuesta de corrección concisa]
Estado: Pendiente de revisión manual.

4. CORRECCIONES DIRECTAS (Oculto):
Al puro final de tu respuesta, DEBES agregar las instrucciones de reemplazo de texto exacto para todos los errores menores (ortografía, concordancia plural/singular, números por letras, formato, etc.) usando EXACTAMENTE este formato por cada error que requiera corrección en el texto (usa comillas dobles, no uses Markdown ni cursivas). IMPORTANTE: Ignora los espacios en blanco o guiones bajos (______), no propongas correcciones para ellos.
[ERROR: "texto original exacto" -> "texto corregido exacto"]

Finalmente, pregúntame si deseo anexar más archivos (DUI u otros) para revisión cruzada.`;
        handleSendMessage([fileData], customInstruction, `[Documento cargado: ${fileName}]`);
      } catch (err) {
        console.error("Error al extraer texto:", err);
      }
    }
  };

  const handleNewChat = () => {
    const newId = `conv_${Date.now()}_${modality}`;
    setActiveConversations(prev => ({ ...prev, [modality]: newId }));
    setChatsByModality(prev => ({ ...prev, [modality]: [] }));
  };

  const handleSaveDocument = () => {
    const activeTab = editorTabs.find(t => t.id === activeTabId);
    if (!activeTab || !activeTab.content) return;
    
    const htmlContent = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"></head><body style="text-align: justify; font-family: sans-serif;">${activeTab.content}</body></html>`;

    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeTab.title || 'documento'}.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCloseTab = (e, tabId) => {
    e.stopPropagation();
    let newTabs = editorTabs.filter(t => t.id !== tabId);
    if (newTabs.length === 0) {
      newTabs = [{ id: 'tab_default', title: 'Documento 1', content: '' }];
    }
    if (activeTabId === tabId) {
      setActiveTabId(newTabs[newTabs.length - 1].id);
    }
    setEditorTabs(newTabs);
  };

  const escapeRegExp = (string) => {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  };

  const replaceNthOccurrence = (str, regex, replacement, n) => {
    let count = 0;
    return str.replace(new RegExp(regex.source, 'gi'), match => {
      if (count === n) {
        count++;
        return typeof replacement === 'function' ? replacement(match) : replacement;
      }
      count++;
      return match;
    });
  };

  const handleCorrectError = (originalText, correctedText, index = 0, errorKey) => {
    setEditorTabs(prevTabs => {
      return prevTabs.map(tab => {
        if (tab.id === activeTabId) {
          let newContent = tab.content;
          const replacementHtml = `<strong><span style="color: #16a34a">${correctedText}</span></strong>`;
          const highlightRegex = new RegExp(`<mark[^>]*>${escapeRegExp(originalText)}</mark>`, 'gi');
          if (newContent.match(highlightRegex)) {
            newContent = newContent.replace(highlightRegex, replacementHtml);
          } else {
            const regex = new RegExp(`\\b${escapeRegExp(originalText)}\\b`, 'i');
            newContent = replaceNthOccurrence(newContent, regex, replacementHtml, index);
          }
          return { ...tab, content: newContent };
        }
        return tab;
      });
    });
    setCorrectedErrors(prev => new Set(prev).add(errorKey));
  };

  const handleHoverError = (originalText, isHovering, index = 0) => {
    setEditorTabs(prevTabs => {
      return prevTabs.map(tab => {
        if (tab.id === activeTabId) {
          let newContent = tab.content;
          const highlightRegex = new RegExp(`<mark[^>]*>${escapeRegExp(originalText)}</mark>`, 'gi');
          
          if (isHovering && !newContent.match(highlightRegex)) {
            const regex = new RegExp(`\\b${escapeRegExp(originalText)}\\b`, 'i');
            newContent = replaceNthOccurrence(newContent, regex, `<mark>${originalText}</mark>`, index);
            setTimeout(() => {
              const mark = document.querySelector('.ProseMirror mark');
              if (mark) {
                mark.scrollIntoView({ behavior: 'smooth', block: 'center' });
              }
            }, 150); // Increased timeout to ensure Tiptap has updated the DOM
          } else if (!isHovering && newContent.match(highlightRegex)) {
            newContent = newContent.replace(highlightRegex, originalText);
          }
          return { ...tab, content: newContent };
        }
        return tab;
      });
    });
  };

  const renderChatMessage = (text, role) => {
    if (role === 'user') return text;
    const errorRegex = /\[ERROR:\s*"([^"]+)"\s*->\s*"([^"]+)"\]/g;
    
    if (!text.match(errorRegex)) return text;
    
    const parts = [];
    let lastIndex = 0;
    let match;
    
    const regex = /\[ERROR:\s*"([^"]+)"\s*->\s*"([^"]+)"\]/g;
    while ((match = regex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        parts.push(text.substring(lastIndex, match.index));
      }
      const originalText = match[1];
      const correctedText = match[2];
      
      // Calculate how many times it appears in the text and cache it to prevent UI shifting
      const activeTab = editorTabs.find(t => t.id === activeTabId);
      const textContentStr = activeTab ? activeTab.content : '';
      const textMatches = textContentStr.match(new RegExp(`\\b${escapeRegExp(originalText)}\\b`, 'gi'));
      const currentCount = textMatches ? textMatches.length : 1;
      
      const cacheKey = `${match.index}-${originalText}`;
      if (!occurrencesCache.current[cacheKey] || occurrencesCache.current[cacheKey] < currentCount) {
        occurrencesCache.current[cacheKey] = currentCount;
      }
      const occurrencesCount = occurrencesCache.current[cacheKey];
      
      for (let i = 0; i < occurrencesCount; i++) {
        const errorKey = `${match.index}-${i}`;
        const isCorrected = correctedErrors.has(errorKey);
        
        parts.push(
          <div 
            key={errorKey} 
            className="my-2 p-2 border border-secondary/30 bg-surface-container-low rounded-lg shadow-sm flex flex-col gap-2 transition-all hover:border-secondary"
            onMouseEnter={() => { if (!isCorrected) handleHoverError(originalText, true, i); }}
            onMouseLeave={() => { if (!isCorrected) handleHoverError(originalText, false, i); }}
          >
            <div className="text-xs">
              <span className="line-through text-error mr-2">{originalText}</span>
              <span className="text-primary font-bold">→ {correctedText}</span>
              {occurrencesCount > 1 && <span className="ml-2 text-on-surface-variant italic">(Coincidencia {i + 1})</span>}
            </div>
            {isCorrected ? (
              <div className="self-start text-[11px] text-green-600 font-bold px-2 py-1 flex items-center gap-1">
                <span className="material-symbols-outlined text-[14px]">check_circle</span>
                Corregido
              </div>
            ) : (
              <button
                onClick={() => handleCorrectError(originalText, correctedText, i, errorKey)}
                className="self-start text-[11px] bg-secondary text-on-secondary px-2 py-1 rounded hover:bg-secondary/90 transition-colors"
              >
                Corregir
              </button>
            )}
          </div>
        );
      }
      
      lastIndex = regex.lastIndex;
    }
    
    if (lastIndex < text.length) {
      parts.push(text.substring(lastIndex));
    }
    
    return parts;
  };

  const handleSendMessage = async (overrideFiles = null, overrideMessage = null, overrideDisplay = null) => {
    const isEvent = overrideFiles && overrideFiles.target;
    const filesToUse = (overrideFiles && Array.isArray(overrideFiles) && !isEvent) ? overrideFiles : attachedFiles;
    
    const actualInputValue = (typeof overrideMessage === 'string') ? overrideMessage : inputValue.trim();
    if (!actualInputValue && filesToUse.length === 0) return;
    
    const newMessage = actualInputValue || "Revisa este archivo adjunto.";
    let displayMessage = (typeof overrideDisplay === 'string') ? overrideDisplay : actualInputValue;
    if (!displayMessage && filesToUse.length > 0) {
      displayMessage = `[Archivo adjunto: ${filesToUse.map(f => f.name).join(', ')}]`;
    }
    
    setInputValue("");
    setAttachedFiles([]);
    
    const currentMessages = chatsByModality[modality] || [];
    const updatedMessages = [...currentMessages, { role: "user", parts: [{ text: displayMessage }] }];
    setChatsByModality(prev => ({ ...prev, [modality]: updatedMessages }));
    setIsChatLoading(true);
    
    try {
      const response = await fetch("http://localhost:3001/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          message: newMessage,
          history: currentMessages,
          modality: modality,
          files: filesToUse
        })
      });
      const data = await response.json();
      if (data.response) {
        let finalResponseText = data.response;
        
        if (modality === 'ASESORA' && finalResponseText.split('\n').length > 20) {
          const htmlContent = marked.parse(finalResponseText);
          const currentConvId = activeConversations[modality];
          const tabIdForConv = `asesoria_${currentConvId}`;
          
          setEditorTabs(prevTabs => {
            const existingTabIndex = prevTabs.findIndex(t => t.id === tabIdForConv);
            
            if (existingTabIndex >= 0) {
               // Apend to existing tab for this conversation
               let newTabs = [...prevTabs];
               newTabs[existingTabIndex].content += `<br/><hr/><br/>${htmlContent}`;
               setActiveTabId(tabIdForConv);
               return newTabs;
            } else {
               const asesoriaTabs = prevTabs.filter(t => t.id.startsWith('asesoria_'));
               let newTabs = [...prevTabs];
               if (asesoriaTabs.length >= 3) {
                  newTabs = newTabs.filter(t => t.id !== asesoriaTabs[0].id);
               }
               
               let docType = "DOCUMENTO";
               const msgUpper = newMessage.toUpperCase();
               if (msgUpper.includes("ARRENDAMIENTO")) docType = "ARRENDAMIENTO";
               else if (msgUpper.includes("COMPRA") || msgUpper.includes("VENTA")) docType = "COMPRAVENTA";
               else if (msgUpper.includes("PODER")) docType = "PODER";
               else if (msgUpper.includes("MUTUO")) docType = "MUTUO";
               else if (msgUpper.includes("SOCIEDAD")) docType = "SOCIEDAD";
               else if (msgUpper.includes("LABORAL")) docType = "LABORAL";

               let dynamicTitle = `${docType} - Cliente`;
               const headingMatch = finalResponseText.match(/^#+\s+(.+)$/m);
               if (headingMatch && headingMatch[1]) {
                 dynamicTitle = headingMatch[1].substring(0, 35).toUpperCase();
               }

               const newTab = { id: tabIdForConv, title: dynamicTitle, content: htmlContent };
               newTabs.push(newTab);
               setActiveTabId(tabIdForConv);
               return newTabs;
            }
          });
          
          finalResponseText = "He añadido el análisis detallado a la pestaña ASESORÍA LEGAL de esta conversación.";
          setScrollToLastBlock(true);
        }
        
        setChatsByModality(prev => ({ 
          ...prev, 
          [modality]: [...updatedMessages, { role: "model", parts: [{ text: finalResponseText }], usage: data.usage }] 
        }));
      } else {
        console.error("No response from server:", data);
      }
    } catch (error) {
      console.error("Error sending message:", error);
    } finally {
      setIsChatLoading(false);
    }
  };

  React.useEffect(() => {
    const handleMouseMove = (e) => {
      if (isResizingLeft) {
        setLeftWidth(Math.max(200, Math.min(e.clientX, window.innerWidth * 0.5)));
      } else if (isResizingRight) {
        setRightWidth(Math.max(250, Math.min(window.innerWidth - e.clientX, window.innerWidth * 0.5)));
      }
    };

    const handleMouseUp = () => {
      setIsResizingLeft(false);
      setIsResizingRight(false);
    };

    if (isResizingLeft || isResizingRight) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    };
  }, [isResizingLeft, isResizingRight]);

  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html: `
        /* Custom styles */
        @layer base{html,body{margin:0;padding:0;}body{overscroll-behavior:none;}main>:first-child{margin-top:0!important;}main>:last-child{margin-bottom:0!important;}}::-webkit-scrollbar{display:none;}
        .chat-scrollbar::-webkit-scrollbar { display: block; width: 6px; }
        .chat-scrollbar::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.2); border-radius: 4px; }
        .dark .chat-scrollbar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.2); }
      `,
        }}
      />
      <div className={`${isDarkMode ? 'dark ' : ''}h-screen w-screen overflow-hidden flex flex-col font-body-ui-md bg-background text-on-surface`}>
        <aside 
          className="fixed left-0 top-14 h-[calc(100vh-3.5rem)] bg-surface-container-low z-50 flex flex-col border-r border-outline-variant/30"
          style={{ width: `${leftWidth}px` }}
        >
          <div
            className="absolute right-0 top-0 w-2 h-full cursor-col-resize hover:bg-primary/20 z-50 transition-colors"
            onMouseDown={() => setIsResizingLeft(true)}
          ></div>
          <div className="px-stack-md my-stack-md">
            <button 
              onClick={handleNewChat}
              className="w-full flex items-center justify-center gap-stack-sm bg-primary text-on-primary py-stack-sm rounded-lg font-label-caps hover:bg-primary-container transition-colors"
            >
              <span className="material-symbols-outlined text-[18px]">add</span>
              {t.newChat}
            </button>
          </div>
          <nav
            className="flex-1 px-stack-md overflow-y-auto space-y-1"
            data-active-classes="bg-secondary-container text-on-secondary-container font-bold"
          >
            <div className="text-on-surface-variant font-label-caps text-[10px] px-stack-sm py-stack-sm mt-stack-md">
              Conversaciones
            </div>
            {editorTabs.map(tab => (
              <div
                key={tab.id}
                onClick={(e) => { e.preventDefault(); setActiveTabId(tab.id); }}
                className={`flex items-center justify-between px-stack-sm py-stack-sm rounded-lg transition-all cursor-pointer ${
                  activeTabId === tab.id
                    ? 'bg-secondary-container text-on-secondary-container font-bold'
                    : 'text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface'
                }`}
              >
                <div className="flex items-center overflow-hidden">
                  <span className="material-symbols-outlined mr-3 shrink-0">
                    {tab.id.startsWith('asesoria') ? 'gavel' : 'description'}
                  </span>
                  <span className="truncate">{tab.title}</span>
                </div>
                <button 
                  onClick={(e) => handleCloseTab(e, tab.id)}
                  className="hover:bg-black/10 rounded-full p-1 flex items-center justify-center transition-colors shrink-0"
                >
                  <span className="material-symbols-outlined text-[14px]">close</span>
                </button>
              </div>
            ))}
          </nav>
        </aside>
        <div style={{ paddingLeft: `${leftWidth}px`, paddingRight: `${rightWidth}px` }}>
          <header className="fixed top-0 left-0 w-full h-14 bg-white border-b border-[#cac4d0]/30 z-[60] flex items-center justify-between px-stack-lg">
            <div className="flex items-center">
              <img src="/logo.png" alt="LexIA Logo" className="h-8 w-auto object-contain" />
            </div>
            <div className="flex items-center gap-stack-md">
              <button 
                onClick={() => setIsDarkMode(!isDarkMode)}
                className="flex items-center justify-center text-[#49454f] hover:text-[#1c1b1f] transition-colors hover:bg-black/5 w-8 h-8 rounded-md"
                title={isDarkMode ? "Modo Claro" : "Modo Oscuro"}
              >
                <span className="material-symbols-outlined text-[18px]">
                  {isDarkMode ? "light_mode" : "dark_mode"}
                </span>
              </button>
              <div className="relative">
                <button 
                  onClick={() => setLangMenuOpen(!langMenuOpen)}
                  className="flex items-center gap-1 text-[#49454f] hover:text-[#1c1b1f] transition-colors hover:bg-black/5 px-2 py-1 rounded-md"
                >
                  <span className="material-symbols-outlined text-[18px]">
                    language
                  </span>
                  <span className="text-xs font-bold text-[#1c1b1f]">{currentLang}</span>
                  <span className="material-symbols-outlined text-[16px]">
                    expand_more
                  </span>
                </button>
                {langMenuOpen && (
                  <div className="absolute top-full right-0 mt-1 w-32 bg-white border border-[#cac4d0]/30 rounded-lg shadow-lg py-1 z-50 flex flex-col">
                    <button 
                      onClick={() => {setCurrentLang('ES'); setLangMenuOpen(false);}}
                      className={`text-left px-3 py-2 text-sm hover:bg-black/5 transition-colors ${currentLang === 'ES' ? 'text-primary font-bold' : 'text-[#1c1b1f]'}`}
                    >
                      {t.langEs}
                    </button>
                    <button 
                      onClick={() => {setCurrentLang('EN'); setLangMenuOpen(false);}}
                      className={`text-left px-3 py-2 text-sm hover:bg-black/5 transition-colors ${currentLang === 'EN' ? 'text-primary font-bold' : 'text-[#1c1b1f]'}`}
                    >
                      {t.langEn}
                    </button>
                  </div>
                )}
              </div>
              <div className="h-6 w-px bg-[#cac4d0]/50 mx-stack-sm"></div>
              <img
                src="https://lh3.googleusercontent.com/aida-public/AB6AXuCyXLlLzzfKIXyZ7QV5sGUY5NBYGpc7lScZtY1d7nF9GL2OPnyfZ0IrdSYcLq1Jx2zpKF819l77qRw-N2hhyLaHqbsdgj1ATdvHGg1t1s4jv3EMWgvffwH4HXxM3A26hQYdLqZMW6E-Oo8w_5CkLHVA1U9tZoMf08y6aLdqmM0n_3aCJq-mHQuO9vubDgH8qqM1aFrhoyR3eH1-8fswrA_M_9qNnINtVxYDP4hZvyntdUM-Jc0uTWGgUZJtyrY3UPk8iXc"
                alt="User Avatar"
                className="h-8 w-auto object-contain rounded-full"
              />
            </div>
          </header>
          <main className="relative pt-14 min-h-screen bg-surface">
            <div className="flex flex-col w-full h-full relative font-body-md bg-surface text-on-surface">
              <div className="flex w-full h-[calc(100vh-3.5rem)]">
                <section className="flex-1 h-full flex flex-col bg-surface relative overflow-hidden">
                  <div className="h-12 bg-surface flex items-center px-6 gap-2 text-on-surface-variant flex-shrink-0 z-10 sticky top-0 shadow-[0_4px_24px_-12px_rgba(0,0,0,0.05)]">
                    <div className="flex items-center gap-1">
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center font-bold text-lg bg-surface-container-low text-primary shadow-[inset_0_1px_2px_rgba(255,255,255,0.8)] shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
                        B
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center italic text-lg">
                        I
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center underline text-lg">
                        U
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center line-through text-lg text-outline">
                        S
                      </button>
                    </div>
                    <div className="w-px h-5 bg-outline-variant/40 mx-2"></div>
                    <div className="flex items-center gap-1">
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_left
                        </span>
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_center
                        </span>
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_justify
                        </span>
                      </button>
                    </div>
                    <div className="w-px h-5 bg-outline-variant/40 mx-2"></div>
                    <div className="flex items-center gap-1">
                      <button className="px-3 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center gap-1">
                        <span className="text-sm font-medium">{t.heading2}</span>
                        <span className="material-symbols-outlined text-[16px]">
                          expand_more
                        </span>
                      </button>
                    </div>
                    <div className="flex-1">
                      <div className="flex justify-center items-center h-full opacity-20">
                        <img
                          src="https://lh3.googleusercontent.com/aida-public/AB6AXuDLOMTUQRJqbAc2Wbu0-aIUU0FNgVYFFVeYT2A_NPfB94GNLWtE9J0ZGFYwUHiFI8VY7lRk5BPQDydr9zsfnBK1w35u5qz1_NhbSFS1nBR_UhN_MFKsWFJeEcSaAIPQFF81BmgRXBGXz8WJmNsrCrMnG7I7m5k2nM2_X5dJk-UCHGfJXZp9puHk9sjvIkhdphGUqn0KOGrXHZ4v4KclvuFQci8zHMBk29YcFhwOdWyzZMXyRNzMWCMSr686HH1I1DNNzLU"
                          className="h-6 w-6 object-contain"
                        />
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button onClick={handleSaveDocument} className="h-8 px-3 rounded-lg bg-[#2B579A] text-white hover:bg-[#1E3E6D] transition-colors flex items-center gap-1.5 shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
                        <span className="material-symbols-outlined text-[16px]">
                          save
                        </span>
                        <span className="text-[13px] font-medium">Guardar</span>
                      </button>
                    </div>
                  </div>

                  {/* Pestañas (Tabs) en el editor */}
                  <div className="flex bg-surface-container-low border-b border-outline-variant/30 px-6 pt-2">
                    {editorTabs.map(tab => (
                       <div
                         key={tab.id}
                         onClick={() => setActiveTabId(tab.id)}
                         className={`flex items-center gap-2 py-2 px-4 text-sm font-medium border-b-2 transition-colors cursor-pointer ${
                           activeTabId === tab.id
                             ? 'border-primary text-primary'
                             : 'border-transparent text-on-surface-variant hover:text-on-surface hover:border-outline-variant'
                         }`}
                       >
                         <span className="truncate max-w-[150px]">{tab.title}</span>
                         <button 
                           onClick={(e) => handleCloseTab(e, tab.id)}
                           className="hover:bg-black/10 rounded-full w-4 h-4 flex items-center justify-center transition-colors"
                         >
                           <span className="material-symbols-outlined text-[12px]">close</span>
                         </button>
                       </div>
                    ))}
                  </div>

                  <div className="flex-1 overflow-y-auto px-8 py-12 relative flex justify-center pb-32 chat-scrollbar">
                    <div className="w-full max-w-[760px] bg-surface-container-lowest min-h-[900px] shadow-[0_8px_30px_-4px_rgba(0,0,0,0.08)] shadow-[0_4px_12px_-2px_rgba(0,0,0,0.03)] px-16 py-20 relative group text-[#2d3133] prose prose-sm sm:prose-base max-w-none">
                      <div className="h-full min-h-[500px]">
                        {editorTabs.map(tab => (
                          <div key={tab.id} style={{ display: activeTabId === tab.id ? 'block' : 'none' }} className="w-full h-full">
                            <TiptapEditor 
                              content={tab.content} 
                              onChange={(newContent) => {
                                setEditorTabs(prev => prev.map(t => t.id === tab.id ? { ...t, content: newContent } : t));
                              }} 
                            />
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </main>
        </div>
      <aside
        className="fixed right-0 top-14 h-[calc(100vh-3.5rem)] bg-surface-container-lowest border-l border-outline-variant/30 z-50 flex flex-col"
        style={{ width: `${rightWidth}px` }}
      >
        <div
          className="absolute left-0 top-0 w-2 h-full cursor-col-resize hover:bg-primary/20 z-50 transition-colors"
          onMouseDown={() => setIsResizingRight(true)}
        ></div>
        <div className="w-full h-full flex flex-col">
          <div className="h-14 flex items-center px-stack-md border-b border-outline-variant/20 bg-surface-container-low">
            <div className="w-10 h-10 rounded-full overflow-hidden border border-outline-variant/30 mr-3 shrink-0">
              <img
                src={isDarkMode ? "/mascota-oscuro.png" : "https://lh3.googleusercontent.com/aida-public/AB6AXuBdKMOoSQ45-xqB_Cf9hAjG79pYqVNrkQo0xpMw0a2clEYC7rxCw-B-3S7yiH9OcrpypudA2k3MWsv8mPnjuo3T7UwX0SmWwsVhFlA75qq-quCQzEm07FI43mUZqz0jP6MVzfw-CcDmeRVATpsITUvserdRufUUS3wSoMnI43lwsOpGFN4MsEWNanNs0Rm4WnTqdp9UhJ3c1S6FIuq7SXrinPmQ6-moBD4jM3XFqRuDU5GD7Io5iJ6rCgPg7c2RFrN3XtA"}
                className="w-full h-full object-cover"
                alt="AI Mascot"
              />
            </div>
            <div className="flex bg-surface-container-highest rounded-lg p-1 border border-outline-variant/20 gap-1">
              {[
                { id: 'ASISTENTE', icon: 'support_agent', title: t.createBtnDesc },
                { id: 'ASESORA', icon: 'balance', title: t.adviseBtnDesc },
                { id: 'AUDITORA', icon: 'fact_check', title: t.reviewBtnDesc }
              ].map(mod => (
                <button
                  key={mod.id}
                  onClick={() => setModality(mod.id)}
                  title={mod.title}
                  className={`flex items-center gap-1 px-2.5 py-1.5 rounded-md text-[10px] font-bold transition-all ${
                    modality === mod.id
                      ? 'bg-surface shadow-sm text-primary'
                      : 'text-on-surface-variant hover:text-on-surface hover:bg-surface/50'
                  }`}
                >
                  <span className="material-symbols-outlined text-[14px]">{mod.icon}</span>
                  {mod.id}
                </button>
              ))}
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-stack-md space-y-stack-md flex flex-col chat-scrollbar">
            {(chatsByModality[modality] || []).length === 0 ? (
              <div className="bg-surface-container p-stack-sm rounded-lg text-xs text-on-surface-variant border-l-4 border-secondary flex flex-col gap-2 items-start">
                {modality === 'ASISTENTE' && <span>¿Qué documento quieres que creemos?</span>}
                {modality === 'ASESORA' && <span>Hola, soy LexIA tu asesora legal. ¿En qué puedo ayudarle ahora?</span>}
                {modality === 'AUDITORA' && (
                  <>
                    <span>¿Qué documento desea analizar?</span>
                    <button 
                      onClick={() => fileInputRefAuditora.current.click()} 
                      className="bg-primary text-on-primary px-3 py-1.5 rounded-md text-[11px] font-bold hover:bg-primary/90 transition-colors"
                    >
                      Añadir documento
                    </button>
                  </>
                )}
              </div>
            ) : (
              (chatsByModality[modality] || []).map((msg, idx) => (
                <div key={idx} className={`p-3 rounded-lg text-sm max-w-[85%] ${msg.role === 'user' ? 'bg-primary text-on-primary self-end whitespace-pre-wrap' : 'bg-surface-container text-on-surface self-start whitespace-pre-wrap flex flex-col gap-2'}`}>
                  {renderChatMessage(msg.parts[0].text, msg.role)}
                  {msg.usage && msg.usage.totalTokenCount && (
                    <div className="flex gap-2 self-start mt-1">
                      <div className="bg-secondary/10 border border-secondary/30 text-secondary text-[10px] px-2 py-1 rounded-md font-bold flex items-center gap-1">
                        <span className="material-symbols-outlined text-[12px]">data_usage</span>
                        Tokens: {msg.usage.totalTokenCount}
                      </div>
                      <div className="bg-secondary/10 border border-secondary/30 text-secondary text-[10px] px-2 py-1 rounded-md font-bold flex items-center gap-1" title="Costo aproximado (Gemini 1.5 Flash API)">
                        <span className="material-symbols-outlined text-[12px]">payments</span>
                        Costo aprox: ${(msg.usage.promptTokenCount * 0.15 / 1000000 + msg.usage.candidatesTokenCount * 0.60 / 1000000).toFixed(5)} USD
                      </div>
                    </div>
                  )}
                </div>
              ))
            )}
            {isChatLoading && (
              <div className="p-3 rounded-lg text-sm max-w-[85%] bg-surface-container text-on-surface self-start animate-pulse">
                Escribiendo...
              </div>
            )}
            <div ref={chatEndRef} />
          </div>
          <div className="p-stack-md border-t border-outline-variant/20 bg-surface-container-low">
            {attachedFiles.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-2">
                {attachedFiles.map((file, idx) => (
                  <div key={idx} className="bg-surface-container-high text-xs px-2 py-1 rounded-md flex items-center gap-1 text-on-surface">
                    <span className="material-symbols-outlined text-[14px]">
                      {file.type.startsWith('image/') ? 'image' : 'description'}
                    </span>
                    <span className="truncate max-w-[150px]">{file.name}</span>
                    <button 
                      onClick={() => setAttachedFiles(prev => prev.filter((_, i) => i !== idx))}
                      className="hover:text-primary transition-colors flex items-center"
                    >
                      <span className="material-symbols-outlined text-[14px]">close</span>
                    </button>
                  </div>
                ))}
              </div>
            )}
            <div className="relative">
              <textarea
                className={`w-full bg-surface-container-lowest border border-outline-variant rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-secondary resize-none h-24 ${modality === 'ASESORA' ? 'pl-10 pr-10 py-stack-sm' : 'p-stack-sm'} ${modality === 'AUDITORA' ? 'opacity-50 cursor-not-allowed bg-surface-container' : ''}`}
                placeholder={modality === 'AUDITORA' ? "Chat deshabilitado (Use el botón 'Añadir documento' arriba)" : t.askPlaceholder}
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                disabled={modality === 'AUDITORA'}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleSendMessage();
                  }
                }}
              ></textarea>
              {modality === 'ASESORA' && (
                <div className="absolute left-3 bottom-3">
                  <button
                    onClick={() => fileInputRef.current.click()}
                    className="text-on-surface-variant hover:text-primary transition-colors flex items-center justify-center"
                    title="Adjuntar archivo o imagen"
                  >
                    <span className="material-symbols-outlined">attach_file</span>
                  </button>
                  <input
                    type="file"
                    multiple
                    ref={fileInputRef}
                    style={{ display: 'none' }}
                    onChange={handleFileChange}
                    accept="image/*,application/pdf"
                  />
                </div>
              )}
              <input
                type="file"
                multiple
                ref={fileInputRefAuditora}
                style={{ display: 'none' }}
                onChange={handleAuditoraFileChange}
                accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain"
              />
              <button 
                onClick={handleSendMessage}
                disabled={isChatLoading || modality === 'AUDITORA'}
                className="absolute right-2 bottom-2 text-secondary hover:text-on-secondary-container transition-colors disabled:opacity-50"
              >
                <span className="material-symbols-outlined">send</span>
              </button>
            </div>
          </div>
        </div>
      </aside>
      </div>
    </>
  );
}
