"use client";
import React from "react";
import { marked } from "marked";
import TiptapEditor from "../components/TiptapEditor";

const translations = {
  ES: {
    newChat: "NUEVO CHAT",
    actions: "ACCIONES",
    createDoc: "Crear Documento",
    reviewDoc: "Revisar Documento",
    cases: "Casos",
    saved: "Guardado",
    share: "Compartir",
    export: "Exportar",
    heading2: "Título 2",
    comment: "Comentar",
    aiTools: "Herramientas IA",
    pageInfo: "Página 1 / 4",
    confidentialDraft: "Borrador Confidencial",
    docTitle: "CONTRATO DE ARRENDAMIENTO COMERCIAL",
    docP1: "Este Contrato de Arrendamiento Comercial (el \"Contrato\") se celebra este",
    docDate: "15 de octubre de 2023",
    docP2: ", por y entre:",
    docLandlord: "Propietario:",
    docLandlordDesc: "Horizon Property Management LLC, una corporación organizada bajo las leyes de Delaware, con sede en 100 Financial District Blvd, New York, NY (\"Propietario\").",
    docTenant: "Inquilino:",
    docTenantDesc: "Nexus Technology Group Inc., una corporación organizada bajo las leyes de California, con sede en 450 Innovation Drive, San Francisco, CA (\"Inquilino\").",
    grantOfLease: "1. Otorgamiento del Arrendamiento",
    grantOfLeaseDesc: "El Propietario, en consideración al alquiler a pagar y a los acuerdos a cumplir por parte del Inquilino, por la presente arrienda al Inquilino la propiedad descrita en el Anexo A adjunto (las \"Instalaciones\").",
    generatedBy: "Generado por LexIA",
    permittedUse: "2. Uso Permitido",
    permittedUseDesc1: "El Inquilino deberá usar y ocupar las Instalaciones únicamente para el propósito de operar una oficina de desarrollo tecnológico y funciones administrativas. El Inquilino no permitirá que las Instalaciones se usen para ningún propósito ilegal ni de manera que perturbe a otros. ",
    permittedUseDesc2: "El Inquilino tiene estrictamente prohibido almacenar materiales peligrosos en las Instalaciones.",
    term: "3. Plazo",
    termDesc: "El plazo de este Arrendamiento será por un período de sesenta (60) meses, comenzando el 1 de noviembre de 2023, y terminando el 31 de octubre de 2028, a menos que termine antes según las disposiciones del presente.",
    instructPlaceholder: "Instruye a LexIA para reescribir, resumir o añadir cláusulas...",
    generate: "GENERAR",
    aiAssistant: "ASISTENTE IA",
    assistantMessage: "Estoy analizando la sección de responsabilidad de 'Smith v. GlobalCorp'. ¿En qué te puedo ayudar con tu borrador?",
    askPlaceholder: "Pregúntale a LexIA...",
    createBtn: "CREAR",
    createBtnDesc: "Generar documentos desde cero",
    adviseBtn: "ASESORAR",
    adviseBtnDesc: "Resolver consultas o casos legales",
    reviewBtn: "REVISAR",
    reviewBtnDesc: "Analizar documentos subidos",
    langEs: "Español (ES)",
    langEn: "English (EN)",
  },
  EN: {
    newChat: "NEW CHAT",
    actions: "ACTIONS",
    createDoc: "Create Document",
    reviewDoc: "Review Document",
    cases: "Cases",
    saved: "Saved",
    share: "Share",
    export: "Export",
    heading2: "Heading 2",
    comment: "Comment",
    aiTools: "AI Tools",
    pageInfo: "Page 1 / 4",
    confidentialDraft: "Confidential Draft",
    docTitle: "COMMERCIAL LEASE AGREEMENT",
    docP1: "This Commercial Lease Agreement (the \"Agreement\") is made and entered into on this",
    docDate: "15th day of October, 2023",
    docP2: ", by and between:",
    docLandlord: "Landlord:",
    docLandlordDesc: "Horizon Property Management LLC, a corporation organized under the laws of Delaware, with its principal place of business at 100 Financial District Blvd, New York, NY (\"Landlord\").",
    docTenant: "Tenant:",
    docTenantDesc: "Nexus Technology Group Inc., a corporation organized under the laws of California, with its principal place of business at 450 Innovation Drive, San Francisco, CA (\"Tenant\").",
    grantOfLease: "1. Grant of Lease",
    grantOfLeaseDesc: "Landlord, in consideration of the rent to be paid and the covenants and agreements to be performed and observed by the Tenant, does hereby lease to the Tenant and the Tenant does hereby lease and take from the Landlord the property described in Exhibit A attached hereto (the \"Premises\").",
    generatedBy: "Generated by LexIA",
    permittedUse: "2. Permitted Use",
    permittedUseDesc1: "The Tenant shall use and occupy the Premises solely for the purpose of operating a technology development office, general administrative functions, and related business activities. The Tenant shall not use or permit the Premises to be used for any illegal purpose or in any manner that would constitute a nuisance or disturb the quiet enjoyment of other tenants in the building. ",
    permittedUseDesc2: "The Tenant is strictly prohibited from storing hazardous materials on the Premises.",
    term: "3. Term",
    termDesc: "The term of this Lease shall be for a period of sixty (60) months, commencing on November 1, 2023 (the \"Commencement Date\"), and terminating on October 31, 2028 (the \"Termination Date\"), unless sooner terminated pursuant to any provision hereof.",
    instructPlaceholder: "Instruct LexIA to rewrite, summarize, or add clauses...",
    generate: "GENERATE",
    aiAssistant: "AI ASSISTANT",
    assistantMessage: "I am analyzing the liability section of 'Smith v. GlobalCorp'. How can I assist with your draft?",
    askPlaceholder: "Ask LexIA...",
    createBtn: "CREATE",
    createBtnDesc: "Generate documents from scratch",
    adviseBtn: "ADVISE",
    adviseBtnDesc: "Resolve legal queries or cases",
    reviewBtn: "REVIEW",
    reviewBtnDesc: "Analyze uploaded documents",
    langEs: "Español (ES)",
    langEn: "English (EN)",
  }
};

export default function LexiaAssistant() {
  const [langMenuOpen, setLangMenuOpen] = React.useState(false);
  const [currentLang, setCurrentLang] = React.useState('ES');
  const [isDarkMode, setIsDarkMode] = React.useState(false);
  const [modality, setModality] = React.useState('ASISTENTE');
  const t = translations[currentLang];
  const [leftWidth, setLeftWidth] = React.useState(280);
  const [rightWidth, setRightWidth] = React.useState(400);
  const [isResizingLeft, setIsResizingLeft] = React.useState(false);
  const [isResizingRight, setIsResizingRight] = React.useState(false);

  const [chatsByModality, setChatsByModality] = React.useState({
    ASISTENTE: [],
    ASESORA: [],
    AUDITORA: []
  });
  
  const [editorTabs, setEditorTabs] = React.useState([
    { id: 'tab_default', title: 'Documento 1', content: '' }
  ]);
  const [activeTabId, setActiveTabId] = React.useState('tab_default');
  
  const [activeConversations, setActiveConversations] = React.useState({
    ASISTENTE: `conv_${Date.now()}_ASISTENTE`,
    ASESORA: `conv_${Date.now()}_ASESORA`,
    AUDITORA: `conv_${Date.now()}_AUDITORA`
  });
  
  const [inputValue, setInputValue] = React.useState("");
  const [isChatLoading, setIsChatLoading] = React.useState(false);
  const [attachedFiles, setAttachedFiles] = React.useState([]);
  const fileInputRef = React.useRef(null);
  const chatEndRef = React.useRef(null);
  const [scrollToLastBlock, setScrollToLastBlock] = React.useState(false);

  React.useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatsByModality, modality, isChatLoading]);

  React.useEffect(() => {
    if (scrollToLastBlock) {
      const timer = setTimeout(() => {
        const editorContainers = document.querySelectorAll('.ProseMirror');
        for (const container of editorContainers) {
          if (container.offsetParent !== null) { // if visible
            const hrs = container.querySelectorAll('hr');
            if (hrs.length > 0) {
              hrs[hrs.length - 1].scrollIntoView({ behavior: 'smooth', block: 'start' });
            } else {
              container.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
            break;
          }
        }
        setScrollToLastBlock(false);
      }, 200);
      return () => clearTimeout(timer);
    }
  }, [scrollToLastBlock, editorTabs]);

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files.length > 0) {
      const newFiles = Array.from(e.target.files).map(file => {
        return new Promise((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            resolve({
              name: file.name,
              type: file.type,
              base64: reader.result.split(',')[1] // extract base64
            });
          };
          reader.readAsDataURL(file);
        });
      });
      Promise.all(newFiles).then(files => {
        // Enviar automáticamente al adjuntar
        handleSendMessage(files);
      });
    }
  };

  const handleNewChat = () => {
    const newId = `conv_${Date.now()}_${modality}`;
    setActiveConversations(prev => ({ ...prev, [modality]: newId }));
    setChatsByModality(prev => ({ ...prev, [modality]: [] }));
  };

  const handleSendMessage = async (overrideFiles = null) => {
    // Si overrideFiles es un evento (e.g. onClick), ignorarlo y usar attachedFiles
    const isEvent = overrideFiles && overrideFiles.target;
    const filesToUse = (overrideFiles && Array.isArray(overrideFiles)) ? overrideFiles : attachedFiles;
    
    if (!inputValue.trim() && filesToUse.length === 0) return;
    
    const newMessage = inputValue.trim() || "Revisa este archivo adjunto.";
    let displayMessage = inputValue.trim();
    if (!displayMessage && filesToUse.length > 0) {
      displayMessage = `[Archivo adjunto: ${filesToUse.map(f => f.name).join(', ')}]`;
    }
    
    setInputValue("");
    setAttachedFiles([]);
    
    const currentMessages = chatsByModality[modality] || [];
    const updatedMessages = [...currentMessages, { role: "user", parts: [{ text: displayMessage }] }];
    setChatsByModality(prev => ({ ...prev, [modality]: updatedMessages }));
    setIsChatLoading(true);
    
    try {
      const response = await fetch("http://localhost:3001/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          message: newMessage,
          history: currentMessages,
          modality: modality,
          files: filesToUse
        })
      });
      const data = await response.json();
      if (data.response) {
        let finalResponseText = data.response;
        
        if (modality === 'ASESORA' && finalResponseText.split('\n').length > 20) {
          const htmlContent = marked.parse(finalResponseText);
          const currentConvId = activeConversations[modality];
          const tabIdForConv = `asesoria_${currentConvId}`;
          
          setEditorTabs(prevTabs => {
            const existingTabIndex = prevTabs.findIndex(t => t.id === tabIdForConv);
            
            if (existingTabIndex >= 0) {
               // Apend to existing tab for this conversation
               let newTabs = [...prevTabs];
               newTabs[existingTabIndex].content += `<br/><hr/><br/>${htmlContent}`;
               setActiveTabId(tabIdForConv);
               return newTabs;
            } else {
               // Create new tab
               const asesoriaTabs = prevTabs.filter(t => t.id.startsWith('asesoria_'));
               let newTabs = [...prevTabs];
               if (asesoriaTabs.length >= 3) {
                  newTabs = newTabs.filter(t => t.id !== asesoriaTabs[0].id);
               }
               const newTab = { id: tabIdForConv, title: 'ASESORÍA LEGAL', content: htmlContent };
               newTabs.push(newTab);
               setActiveTabId(tabIdForConv);
               return newTabs;
            }
          });
          
          finalResponseText = "He añadido el análisis detallado a la pestaña ASESORÍA LEGAL de esta conversación.";
          setScrollToLastBlock(true);
        }
        
        setChatsByModality(prev => ({ 
          ...prev, 
          [modality]: [...updatedMessages, { role: "model", parts: [{ text: finalResponseText }] }] 
        }));
      } else {
        console.error("No response from server:", data);
      }
    } catch (error) {
      console.error("Error sending message:", error);
    } finally {
      setIsChatLoading(false);
    }
  };

  React.useEffect(() => {
    const handleMouseMove = (e) => {
      if (isResizingLeft) {
        setLeftWidth(Math.max(200, Math.min(e.clientX, window.innerWidth * 0.5)));
      } else if (isResizingRight) {
        setRightWidth(Math.max(250, Math.min(window.innerWidth - e.clientX, window.innerWidth * 0.5)));
      }
    };

    const handleMouseUp = () => {
      setIsResizingLeft(false);
      setIsResizingRight(false);
    };

    if (isResizingLeft || isResizingRight) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
    } else {
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    };
  }, [isResizingLeft, isResizingRight]);

  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html: `
        /* Custom styles */
        @layer base{html,body{margin:0;padding:0;}body{overscroll-behavior:none;}main>:first-child{margin-top:0!important;}main>:last-child{margin-bottom:0!important;}}::-webkit-scrollbar{display:none;}
        .chat-scrollbar::-webkit-scrollbar { display: block; width: 6px; }
        .chat-scrollbar::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.2); border-radius: 4px; }
        .dark .chat-scrollbar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.2); }
      `,
        }}
      />
      <div className={`${isDarkMode ? 'dark ' : ''}h-screen w-screen overflow-hidden flex flex-col font-body-ui-md bg-background text-on-surface`}>
        <aside 
          className="fixed left-0 top-14 h-[calc(100vh-3.5rem)] bg-surface-container-low z-50 flex flex-col border-r border-outline-variant/30"
          style={{ width: `${leftWidth}px` }}
        >
          <div
            className="absolute right-0 top-0 w-2 h-full cursor-col-resize hover:bg-primary/20 z-50 transition-colors"
            onMouseDown={() => setIsResizingLeft(true)}
          ></div>
          <div className="px-stack-md my-stack-md">
            <button 
              onClick={handleNewChat}
              className="w-full flex items-center justify-center gap-stack-sm bg-primary text-on-primary py-stack-sm rounded-lg font-label-caps hover:bg-primary-container transition-colors"
            >
              <span className="material-symbols-outlined text-[18px]">add</span>
              {t.newChat}
            </button>
          </div>
          <nav
            className="flex-1 px-stack-md overflow-y-auto space-y-1"
            data-active-classes="bg-secondary-container text-on-secondary-container font-bold"
          >
            <div className="text-on-surface-variant font-label-caps text-[10px] px-stack-sm py-stack-sm mt-stack-md">
              Conversaciones
            </div>
            {editorTabs.map(tab => (
              <a
                key={tab.id}
                href="#"
                onClick={(e) => { e.preventDefault(); setActiveTabId(tab.id); }}
                className={`flex items-center px-stack-sm py-stack-sm rounded-lg transition-all ${
                  activeTabId === tab.id
                    ? 'bg-secondary-container text-on-secondary-container font-bold'
                    : 'text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface'
                }`}
              >
                <span className="material-symbols-outlined mr-3">
                  {tab.id.startsWith('asesoria') ? 'gavel' : 'description'}
                </span>
                {tab.title}
              </a>
            ))}
          </nav>
        </aside>
        <div style={{ paddingLeft: `${leftWidth}px`, paddingRight: `${rightWidth}px` }}>
          <header className="fixed top-0 left-0 w-full h-14 bg-white border-b border-[#cac4d0]/30 z-[60] flex items-center justify-between px-stack-lg">
            <div className="flex items-center">
              <img src="/logo.png" alt="LexIA Logo" className="h-8 w-auto object-contain" />
            </div>
            <div className="flex items-center gap-stack-md">
              <button 
                onClick={() => setIsDarkMode(!isDarkMode)}
                className="flex items-center justify-center text-[#49454f] hover:text-[#1c1b1f] transition-colors hover:bg-black/5 w-8 h-8 rounded-md"
                title={isDarkMode ? "Modo Claro" : "Modo Oscuro"}
              >
                <span className="material-symbols-outlined text-[18px]">
                  {isDarkMode ? "light_mode" : "dark_mode"}
                </span>
              </button>
              <div className="relative">
                <button 
                  onClick={() => setLangMenuOpen(!langMenuOpen)}
                  className="flex items-center gap-1 text-[#49454f] hover:text-[#1c1b1f] transition-colors hover:bg-black/5 px-2 py-1 rounded-md"
                >
                  <span className="material-symbols-outlined text-[18px]">
                    language
                  </span>
                  <span className="text-xs font-bold text-[#1c1b1f]">{currentLang}</span>
                  <span className="material-symbols-outlined text-[16px]">
                    expand_more
                  </span>
                </button>
                {langMenuOpen && (
                  <div className="absolute top-full right-0 mt-1 w-32 bg-white border border-[#cac4d0]/30 rounded-lg shadow-lg py-1 z-50 flex flex-col">
                    <button 
                      onClick={() => {setCurrentLang('ES'); setLangMenuOpen(false);}}
                      className={`text-left px-3 py-2 text-sm hover:bg-black/5 transition-colors ${currentLang === 'ES' ? 'text-primary font-bold' : 'text-[#1c1b1f]'}`}
                    >
                      {t.langEs}
                    </button>
                    <button 
                      onClick={() => {setCurrentLang('EN'); setLangMenuOpen(false);}}
                      className={`text-left px-3 py-2 text-sm hover:bg-black/5 transition-colors ${currentLang === 'EN' ? 'text-primary font-bold' : 'text-[#1c1b1f]'}`}
                    >
                      {t.langEn}
                    </button>
                  </div>
                )}
              </div>
              <div className="h-6 w-px bg-[#cac4d0]/50 mx-stack-sm"></div>
              <img
                src="https://lh3.googleusercontent.com/aida-public/AB6AXuCyXLlLzzfKIXyZ7QV5sGUY5NBYGpc7lScZtY1d7nF9GL2OPnyfZ0IrdSYcLq1Jx2zpKF819l77qRw-N2hhyLaHqbsdgj1ATdvHGg1t1s4jv3EMWgvffwH4HXxM3A26hQYdLqZMW6E-Oo8w_5CkLHVA1U9tZoMf08y6aLdqmM0n_3aCJq-mHQuO9vubDgH8qqM1aFrhoyR3eH1-8fswrA_M_9qNnINtVxYDP4hZvyntdUM-Jc0uTWGgUZJtyrY3UPk8iXc"
                alt="User Avatar"
                className="h-8 w-auto object-contain rounded-full"
              />
            </div>
          </header>
          <main className="relative pt-14 min-h-screen bg-surface">
            <div className="flex flex-col w-full h-full relative font-body-md bg-surface text-on-surface">
              <div className="flex w-full h-[calc(100vh-3.5rem)]">
                <section className="flex-1 h-full flex flex-col bg-surface relative overflow-hidden">
                  <div className="h-12 bg-surface flex items-center px-6 gap-2 text-on-surface-variant flex-shrink-0 z-10 sticky top-0 shadow-[0_4px_24px_-12px_rgba(0,0,0,0.05)]">
                    <div className="flex items-center gap-1">
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center font-bold text-lg bg-surface-container-low text-primary shadow-[inset_0_1px_2px_rgba(255,255,255,0.8)] shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
                        B
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center italic text-lg">
                        I
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center underline text-lg">
                        U
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center line-through text-lg text-outline">
                        S
                      </button>
                    </div>
                    <div className="w-px h-5 bg-outline-variant/40 mx-2"></div>
                    <div className="flex items-center gap-1">
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_left
                        </span>
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_center
                        </span>
                      </button>
                      <button className="w-8 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center justify-center">
                        <span className="material-symbols-outlined text-[20px]">
                          format_align_justify
                        </span>
                      </button>
                    </div>
                    <div className="w-px h-5 bg-outline-variant/40 mx-2"></div>
                    <div className="flex items-center gap-1">
                      <button className="px-3 h-8 rounded-lg hover:bg-surface-container-high hover:text-on-surface transition-colors flex items-center gap-1">
                        <span className="text-sm font-medium">{t.heading2}</span>
                        <span className="material-symbols-outlined text-[16px]">
                          expand_more
                        </span>
                      </button>
                    </div>
                    <div className="flex-1">
                      <div className="flex justify-center items-center h-full opacity-20">
                        <img
                          src="https://lh3.googleusercontent.com/aida-public/AB6AXuDLOMTUQRJqbAc2Wbu0-aIUU0FNgVYFFVeYT2A_NPfB94GNLWtE9J0ZGFYwUHiFI8VY7lRk5BPQDydr9zsfnBK1w35u5qz1_NhbSFS1nBR_UhN_MFKsWFJeEcSaAIPQFF81BmgRXBGXz8WJmNsrCrMnG7I7m5k2nM2_X5dJk-UCHGfJXZp9puHk9sjvIkhdphGUqn0KOGrXHZ4v4KclvuFQci8zHMBk29YcFhwOdWyzZMXyRNzMWCMSr686HH1I1DNNzLU"
                          className="h-6 w-6 object-contain"
                        />
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button className="h-8 px-3 rounded-lg bg-surface-container text-on-surface hover:bg-surface-container-high transition-colors flex items-center gap-1.5 shadow-[0_1px_3px_rgba(0,0,0,0.05)]">
                        <span className="material-symbols-outlined text-[16px]">
                          add_comment
                        </span>
                        <span className="text-[13px] font-medium">{t.comment}</span>
                      </button>
                      <button className="h-8 px-3 rounded-lg bg-primary-container text-on-primary-container hover:bg-primary-container/90 transition-colors flex items-center gap-1.5 shadow-[0_2px_4px_rgba(13,28,50,0.1)]">
                        <span
                          className="material-symbols-outlined text-[16px]"
                          style={{ fontVariationSettings: "&quot" }}
                        >
                          magic_button
                        </span>
                        <span className="text-[13px] font-medium">
                          {t.aiTools}
                        </span>
                      </button>
                    </div>
                  </div>

                  {/* Pestañas (Tabs) en el editor */}
                  <div className="flex bg-surface-container-low border-b border-outline-variant/30 px-6 pt-2">
                    {editorTabs.map(tab => (
                       <button
                         key={tab.id}
                         onClick={() => setActiveTabId(tab.id)}
                         className={`py-2 px-4 text-sm font-medium border-b-2 transition-colors ${
                           activeTabId === tab.id
                             ? 'border-primary text-primary'
                             : 'border-transparent text-on-surface-variant hover:text-on-surface hover:border-outline-variant'
                         }`}
                       >
                         {tab.title}
                       </button>
                    ))}
                  </div>

                  <div className="flex-1 overflow-y-auto px-8 py-12 relative flex justify-center pb-32 chat-scrollbar">
                    <div className="w-full max-w-[760px] bg-surface-container-lowest min-h-[900px] shadow-[0_8px_30px_-4px_rgba(0,0,0,0.08)] shadow-[0_4px_12px_-2px_rgba(0,0,0,0.03)] px-16 py-20 relative group text-[#2d3133] prose prose-sm sm:prose-base max-w-none">
                      <div className="h-full min-h-[500px]">
                        {editorTabs.map(tab => (
                          <div key={tab.id} style={{ display: activeTabId === tab.id ? 'block' : 'none' }} className="w-full h-full">
                            <TiptapEditor 
                              content={tab.content} 
                              onChange={(newContent) => {
                                setEditorTabs(prev => prev.map(t => t.id === tab.id ? { ...t, content: newContent } : t));
                              }} 
                            />
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </main>
        </div>
      <aside
        className="fixed right-0 top-14 h-[calc(100vh-3.5rem)] bg-surface-container-lowest border-l border-outline-variant/30 z-50 flex flex-col"
        style={{ width: `${rightWidth}px` }}
      >
        <div
          className="absolute left-0 top-0 w-2 h-full cursor-col-resize hover:bg-primary/20 z-50 transition-colors"
          onMouseDown={() => setIsResizingRight(true)}
        ></div>
        <div className="w-full h-full flex flex-col">
          <div className="h-14 flex items-center px-stack-md border-b border-outline-variant/20 bg-surface-container-low">
            <div className="w-10 h-10 rounded-full overflow-hidden border border-outline-variant/30 mr-3 shrink-0">
              <img
                src={isDarkMode ? "/mascota-oscuro.png" : "https://lh3.googleusercontent.com/aida-public/AB6AXuBdKMOoSQ45-xqB_Cf9hAjG79pYqVNrkQo0xpMw0a2clEYC7rxCw-B-3S7yiH9OcrpypudA2k3MWsv8mPnjuo3T7UwX0SmWwsVhFlA75qq-quCQzEm07FI43mUZqz0jP6MVzfw-CcDmeRVATpsITUvserdRufUUS3wSoMnI43lwsOpGFN4MsEWNanNs0Rm4WnTqdp9UhJ3c1S6FIuq7SXrinPmQ6-moBD4jM3XFqRuDU5GD7Io5iJ6rCgPg7c2RFrN3XtA"}
                className="w-full h-full object-cover"
                alt="AI Mascot"
              />
            </div>
            <div className="flex bg-surface-container-highest rounded-lg p-1 border border-outline-variant/20 gap-1">
              {[
                { id: 'ASISTENTE', icon: 'support_agent', title: t.createBtnDesc },
                { id: 'ASESORA', icon: 'balance', title: t.adviseBtnDesc },
                { id: 'AUDITORA', icon: 'fact_check', title: t.reviewBtnDesc }
              ].map(mod => (
                <button
                  key={mod.id}
                  onClick={() => setModality(mod.id)}
                  title={mod.title}
                  className={`flex items-center gap-1 px-2.5 py-1.5 rounded-md text-[10px] font-bold transition-all ${
                    modality === mod.id
                      ? 'bg-surface shadow-sm text-primary'
                      : 'text-on-surface-variant hover:text-on-surface hover:bg-surface/50'
                  }`}
                >
                  <span className="material-symbols-outlined text-[14px]">{mod.icon}</span>
                  {mod.id}
                </button>
              ))}
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-stack-md space-y-stack-md flex flex-col chat-scrollbar">
            {(chatsByModality[modality] || []).length === 0 ? (
              <div className="bg-surface-container p-stack-sm rounded-lg text-xs text-on-surface-variant border-l-4 border-secondary">
                {modality === 'ASISTENTE' && '¿Qué documento quieres que creemos?'}
                {modality === 'ASESORA' && 'Comienza un intake'}
                {modality === 'AUDITORA' && '¿Qué documento deseas revisar?'}
              </div>
            ) : (
              (chatsByModality[modality] || []).map((msg, idx) => (
                <div key={idx} className={`p-3 rounded-lg text-sm max-w-[85%] ${msg.role === 'user' ? 'bg-primary text-on-primary self-end whitespace-pre-wrap' : 'bg-surface-container text-on-surface self-start whitespace-pre-wrap'}`}>
                  {msg.parts[0].text}
                </div>
              ))
            )}
            {isChatLoading && (
              <div className="p-3 rounded-lg text-sm max-w-[85%] bg-surface-container text-on-surface self-start animate-pulse">
                Escribiendo...
              </div>
            )}
            <div ref={chatEndRef} />
          </div>
          <div className="p-stack-md border-t border-outline-variant/20 bg-surface-container-low">
            {attachedFiles.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-2">
                {attachedFiles.map((file, idx) => (
                  <div key={idx} className="bg-surface-container-high text-xs px-2 py-1 rounded-md flex items-center gap-1 text-on-surface">
                    <span className="material-symbols-outlined text-[14px]">
                      {file.type.startsWith('image/') ? 'image' : 'description'}
                    </span>
                    <span className="truncate max-w-[150px]">{file.name}</span>
                    <button 
                      onClick={() => setAttachedFiles(prev => prev.filter((_, i) => i !== idx))}
                      className="hover:text-primary transition-colors flex items-center"
                    >
                      <span className="material-symbols-outlined text-[14px]">close</span>
                    </button>
                  </div>
                ))}
              </div>
            )}
            <div className="relative">
              <textarea
                className={`w-full bg-surface-container-lowest border border-outline-variant rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-secondary resize-none h-24 ${modality === 'ASESORA' ? 'pl-10 pr-10 py-stack-sm' : 'p-stack-sm'}`}
                placeholder={t.askPlaceholder}
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleSendMessage();
                  }
                }}
              ></textarea>
              {modality === 'ASESORA' && (
                <div className="absolute left-3 bottom-3">
                  <button
                    onClick={() => fileInputRef.current.click()}
                    className="text-on-surface-variant hover:text-primary transition-colors flex items-center justify-center"
                    title="Adjuntar archivo o imagen"
                  >
                    <span className="material-symbols-outlined">attach_file</span>
                  </button>
                  <input
                    type="file"
                    multiple
                    ref={fileInputRef}
                    style={{ display: 'none' }}
                    onChange={handleFileChange}
                    accept="image/*,application/pdf"
                  />
                </div>
              )}
              <button 
                onClick={handleSendMessage}
                disabled={isChatLoading}
                className="absolute right-2 bottom-2 text-secondary hover:text-on-secondary-container transition-colors disabled:opacity-50"
              >
                <span className="material-symbols-outlined">send</span>
              </button>
            </div>
          </div>
        </div>
      </aside>
      </div>
    </>
  );
}
